<?php
    $title = 'Base64 Encoder/Decoder';
    $subtitle = 'Javascript Encoder/Decoder using <a href="https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding">WebAPI</a>';
    include('layout/header.phtml');
?>
    <div class="container">
        <p>
            <button type="button" class="btn btn-large btn-success pull-right" id="btn-decode">Decode <span class="glyphicon glyphicon-save-file"></span></button>
            <button type="button" class="btn btn-large btn-danger pull-right" id="btn-encode">Encode <span class="glyphicon glyphicon-open-file"></span></button>
            <button type="button" class="btn btn-large btn-default pull-right" id="btn-example">Example <span class="glyphicon glyphicon-blackboard"></span></button>
        </p>
        <hr />

        <div class="alert alert-danger alert-dismissible" id="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Operation failed: </strong> <code class="txt"></code>
        </div>

        <h3>Input</h3>
        <textarea class="form-control" rows="10" id="text-input"></textarea>

        <h3>Output</h3>
        <textarea class="form-control" rows="10" id="text-output"></textarea>

    </div>

    <?php include('layout/footer.phtml') ?>

    <script type="text/javascript">
        var showError = (function(msg){
            var el = document.id('alert');
            el.getElement('.txt').set('text', msg);
            el.setStyle('display', 'block');
        });

        // load demo data
        document.id('btn-example').addEvent('click', function(){
            document.id('text-input').set('value', document.id('exampleInput').get('html').trim());
        });


        // run transform onclick
        document.id('btn-encode').addEvent('click', function(){
            try {
                document.id('text-output').set('value', btoa(document.id('text-input').get('value')));
            }catch (e){
                showError(e);
            }
        });
        document.id('btn-decode').addEvent('click', function(){
            try{
                document.id('text-output').set('value', atob(document.id('text-input').get('value')));
            }catch (e){
                showError(e);
            }
        });

        // alert dismiss
        document.getElements('.alert-dismissible').each(function(el){
            el.getElement('button.close').addEvent('click', function(){
                el.setStyle('display', 'none');
            });
        });


    </script>

<!-- Lorem Ipsum Testdata !-->
<script type="text/template" id="exampleInput">
    CiAgICBMb3JlbSBpcHN1bSBkb2xvciBzaXQgYW1ldCwgY29uc2V0ZXR1ciBzYWRpcHNjaW5nIGVsaXRyLCBzZWQgZGlhbSBub251bXkgZWlybW9kIHRlbXBvciBpbnZpZHVudCB1dCBsYWJvcmUgZXQgZG9sb3JlIG1hZ25hIGFsaXF1eWFtIGVyYXQsIHNlZCBkaWFtIHZvbHVwdHVhLiBBdCB2ZXJvIGVvcyBldCBhY2N1c2FtIGV0IGp1c3RvIGR1byBkb2xvcmVzIGV0IGVhIHJlYnVtLiBTdGV0IGNsaXRhIGthc2QgZ3ViZXJncmVuLCBubyBzZWEgdGFraW1hdGEgc2FuY3R1cyBlc3QgTG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQuIExvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0LCBjb25zZXRldHVyIHNhZGlwc2NpbmcgZWxpdHIsIHNlZCBkaWFtIG5vbnVteSBlaXJtb2QgdGVtcG9yIGludmlkdW50IHV0IGxhYm9yZSBldCBkb2xvcmUgbWFnbmEgYWxpcXV5YW0gZXJhdCwgc2VkIGRpYW0gdm9sdXB0dWEuIEF0IHZlcm8gZW9zIGV0IGFjY3VzYW0gZXQganVzdG8gZHVvIGRvbG9yZXMgZXQgZWEgcmVidW0uIFN0ZXQgY2xpdGEga2FzZCBndWJlcmdyZW4sIG5vIHNlYSB0YWtpbWF0YSBzYW5jdHVzIGVzdCBMb3JlbSBpcHN1bSBkb2xvciBzaXQgYW1ldC4K</script>
</body>
</html>