<?php
    $title = 'Token Generator';
    $subtitle = 'Generate random Tokens';
    include('layout/header.phtml');
?>

<div class="container">
    <p>
        <button type="button" class="btn btn-large btn-success pull-right" id="start">Generate <span class="glyphicon glyphicon-console"></span></button>
    </p>
    <hr />

    <div class="input-group" style="width: 50%;margin-left: 25%">
        <div class="input-group-addon"><strong>Generator Mode</strong></div>
        <select size="1" id="presetList" class="form-control">
            <option value="wp">WordPress Secrets - (AlphaNum + Special Chars)</option>
            <option value="t20">T20 - (AlphaNum Chars)</option>
            <option value="t32">T32 - (AlphaNum Chars)</option>
            <option value="t64">T64 - (AlphaNum Chars)</option>
            <option value="s20">S20 - (AlphaNum + Special Chars)</option>
            <option value="s32">S32 - (AlphaNum + Special Chars)</option>
            <option value="s64">S64 - (AlphaNum + Special Chars)</option>
        </select>
    </div>

    <hr />

    <h3 class="left">Tokens</h3>
    <textarea class="form-control" rows="15" id="output"></textarea>
</div>

<?php include('layout/footer.phtml') ?>

<script type="text/javascript">
    window.addEvent('domready', function(){
        // character classes
        var cc_numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
        var cc_special = ['#', '.', ':', ',', ';', '-', '_', '+', '~', '*', '?', '}', '=', ']', ')', '[', '(', '{', '/', '&', '%', '$', '§', '!', '@', '<', '>', '|', '^', '°'];
        var cc_general_uc = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'];
        var cc_general_lc = cc_general_uc.map(function(e){
            return e.toLowerCase();
        });

        // alpha numercial
        var cc_alpha = cc_numbers.concat(cc_general_lc, cc_general_uc);

        // alpha numercial + special
        var cc_alphaspecial = cc_numbers.concat(cc_general_lc, cc_general_uc, cc_special);

        // Helper
        var getRandomByClass = (function(n, e){
            var c = '';
            for (var i=0;i<n;i++){
                c += e[Number.random(0, e.length-1)];
            }
            return c;
        });

        var appendNTimes = (function(n, cb, args){
            var buffer = '';

            // call the function n-times with array of given args
            for (var i=0;i<n;i++){
                buffer += cb.apply(this, args) + '\n';
            }
            return buffer;
        });

        // wordpress secrets
        var wpSecrets = (function(){
            var keys = ['AUTH_KEY', 'SECURE_AUTH_KEY', 'LOGGED_IN_KEY', 'NONCE_KEY', 'AUTH_SALT', 'SECURE_AUTH_SALT', 'LOGGED_IN_SALT', 'NONCE_SALT'];
            var buffer = '';

            // call the function n-times with array of given args
            keys.each(function(key){
                buffer +=  'define(\'' + key + '\', \'' + getRandomByClass(64, cc_alphaspecial) + '\');\n';
            });
           
            return buffer;
        });

        // presets
        document.id('start').addEvent('click', function(){
            // output
            var output = '';

            switch (document.id('presetList').value){
                case 'wp':
                    output =  wpSecrets();
                    break;
                case 't20':
                    output =  appendNTimes(10, getRandomByClass, [20, cc_alpha]);
                    break;
                case 't32':
                    output =  appendNTimes(10, getRandomByClass, [32, cc_alpha]);
                    break;
                case 't64':
                    output =  appendNTimes(10, getRandomByClass, [64, cc_alpha]);
                    break;
                case 's20':
                    output =  appendNTimes(10, getRandomByClass, [20, cc_alphaspecial]);
                    break;
                case 's32':
                    output =  appendNTimes(10, getRandomByClass, [32, cc_alphaspecial]);
                    break;
                case 's64':
                    output =  appendNTimes(10, getRandomByClass, [64, cc_alphaspecial]);
                    break;
            }
           
            // set output
            document.id('output').set('value', output);
        });


    });
</script>

</body>
</html>