 <footer>
    <div class="container">
        <hr />
        <p>
            <h4><a href="#"><?php echo $title ?></a> created by <a href="http://andidittrich.de">Andi Dittrich</a></h4>
            It's released under the Terms of <a href="http://opensource.org/licenses/MIT">The MIT License (X11)</a>
            | Page created with <span class="glyphicon glyphicon-hand-right"></span> <a href="http://getbootstrap.com">Bootstrap</a> and driven by the power of <span class="glyphicon glyphicon-wrench"></span> <a href="http://mootools.net">MooTools</a>
            | <span class=" glyphicon glyphicon-heart"></span> <a href="http://glyphicons.com/">Glyhpicons</a>
        </p>
    </div>
</footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/mootools/1.6.0/mootools-core.min.js" integrity="sha384-ny9Ji5u5okyuAV8fZCQqRdFrHzLW+9F+2yidkWx9kg0cS811Srk7u9dDx4zmYMaV" crossorigin="anonymous"></script>